# Generated by Django 2.2.17 on 2021-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
