# Generated by Django 2.2.17 on 2021-04-15 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210415_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'verbose_name': 'Fruit', 'verbose_name_plural': 'Fruits'},
        ),
        migrations.AlterModelOptions(
            name='usersfruits',
            options={'verbose_name': 'User-Fruit', 'verbose_name_plural': 'User-Fruits'},
        ),
        migrations.AlterField(
            model_name='usersfruits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
