# Generated by Django 2.2.17 on 2021-04-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210415_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='fruit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Fruit', verbose_name='Fruit'),
        ),
    ]
