# Generated by Django 2.2.17 on 2021-04-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210415_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfruits',
            name='fruit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Fruit'),
        ),
    ]
