# Generated by Django 2.2.17 on 2021-04-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210415_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.CharField(default='Default', max_length=40, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='isExpired',
            field=models.BooleanField(default=False, verbose_name='IsExpired'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='unit',
            field=models.CharField(default='KG', max_length=40, verbose_name='Unit'),
        ),
    ]
