# Generated by Django 2.2.17 on 2021-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210415_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='bar_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='Barcode'),
        ),
    ]
