# Generated by Django 2.2.17 on 2021-04-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_fruit_bar_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='bar_code',
            new_name='barcode',
        ),
    ]
