# Generated by Django 2.2.17 on 2021-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210417_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='barcode',
            field=models.CharField(blank=True, max_length=120, unique=True, verbose_name='Barcode'),
        ),
    ]
